### ISSUE TITLE
tutorial_diffusion: SmagDiff example not working

### ISSUE THREAD

**Issue by JessCG** [OceanParcels/Parcels#1665]
### Parcels version

3.0.4

### Description

When attempting to run the second example of the tutorial on diffusion (Smagorinsky method) in parcels_tutorial v3.0.4-136-gfcb5c96, I encounter the following error after the cell defining `DeleteParticle`:

`NotImplementedError: Cannot convert 'parcels' used in kernel to C-code`

I am using Python 3.12.5 and Parcels 3.0.4 on a Mac, and have tried the different suggestions provided in the installation instructions to solve compilation errors without luck. I also tried running the tutorial example on another Mac with Python 3.12.0 and Parcels 3.0.0 without success.

Using parcels_tutorial v3.0.0-19-g67d3931, I am able to run the full tutorial on the two setups described above.

Unless there is a known bug in the parcels_tutorial v3.0.0, I can use that version of the tutorial, so I have not investigated further.

### Code sample

```python
# Paste your code within this block
```

```text
# Paste your error message within this block
```

**Comment by erikvansebille** [comment]
Dear @JessCG, thanks for raising this question, and sorry for the confusion. We have changed the code in the tutorial recently, but didn't clarify in readthedocs that version 3.0.4 (which you are using) does not yet support the `parcels.ParcelsRandom` notation.

See https://docs.oceanparcels.org/en/v3.0.4/examples/tutorial_diffusion.html for the way to make the tutorial work in v3.0.4: you should use `ParcelsRandom.normalvariate()` instead of `parcels.ParcelsRandom.normalvariate()`.

**Comment by JessCG** [comment]
Great, thank you for the quick answer and your continued efforts! Now that I understand the issue, I realized that I can find the right version of the tutorial by 
1. downloading the full source code for my parcels version: https://github.com/OceanParcels/Parcels/releases, or
2. selecting the right version and the specific files: https://github.com/OceanParcels/Parcels/tree/v3.0.4/docs/examples

However, even if I select the right Parcels version on ReadtheDocs and click the zipped copy link on Step 4, I seem to get the most recent tutorial.

A quick fix could be to include information on options 1. & 2. above in the installation documentation, or adjust the link in each version of ReadtheDocs to download the relevant code, and not the most recent.

**Comment by VeckoTheGecko** [comment]
> even if I select the right Parcels version on ReadtheDocs and click the zipped copy link on Step 4, I seem to get the most recent tutorial.

I can't recreate this. When I download the `v3.0.4` version and the latest version they're different. Looking at `tutorial_diffusion.ipynb`, I have v3.0.4 on the left, and `latest` on the right.

![image](https://github.com/user-attachments/assets/b4f1ab23-7660-4cb7-9ee2-a71ae5caf348)

When downloaded and unzipped, you should have a folder that is called `parcels_tutorials (v3.0.4)`, perhaps you opened the wrong one?
