### ISSUE TITLE
datetime.timedelta error

### ISSUE THREAD

**Issue by TKzee2027** [OceanParcels/parcels#1030]
# Using globcurrent data v03.0-fv01 - I get this error
'>' not supported between instances of 'datetime.timedelta' and 'int'.  
# I tried removing time from dimensions but I still get the same error

**Comment by reint-fischer** [comment]
Hi @TKzee2027,

Could you maybe share a bit more of the error log and your parcels setup? Where in the simulation does this happen? Do you have a kernel in which you compare two time instances?

**Comment by TKzee2027** [comment]
Hi, Thank you for taking time to read my case. The link to the datasets is here https://drive.google.com/drive/folders/1D1T0_kqWoCQIRE5tDs3eA1KBcSfPIynw?usp=sharing.

filenames = {'U': "GLOB/20*.nc",  'V': "GLOB/20*.nc"}
variables = {'U': 'eastward_eulerian_current_velocity', 'V': 'northward_eulerian_current_velocity'}
dimensions = {'lat': 'lat',  'lon': 'lon', 'time': 'time'}
timestamps = np.expand_dims(np.arange('2016-07-01 T09:00:00', '2016-07-02 T17:05:00',  dtype='datetime64[5m]'),axis=1)
fieldset = FieldSet.from_netcdf(filenames, variables, dimensions, timestamps=timestamps, allow_time_extrapolation=True).

The error starts right after running the last line of code. I get the same error even after removing time from the dimensions:
TypeError                                 Traceback (most recent call last)
<ipython-input-6-76f48f3e1bb2> in <module>()
      6               'lon': 'lon', 'time': 'time'}
      7 timestamps = np.expand_dims(np.arange('2016-07-01T09:00:00', '2016-07-02T17:05:00', dtype='datetime64[5m]'),axis=1)
----> 8 fieldset = FieldSet.from_netcdf(filenames, variables, dimensions, timestamps=timestamps,allow_time_extrapolation=True)

~\Anaconda3\envs\py3_parcels\lib\site-packages\parcels\fieldset.py in from_netcdf(cls, filenames, variables, dimensions, indices, mesh, allow_time_extrapolation, time_periodic, full_load, **kwargs)
    164             fields[var] = Field.from_netcdf(paths, var, dims, inds, mesh=mesh,
    165                                             allow_time_extrapolation=allow_time_extrapolation,
--> 166                                             time_periodic=time_periodic, full_load=full_load, **kwargs)
    167         u = fields.pop('U', None)
    168         v = fields.pop('V', None)

~\Anaconda3\envs\py3_parcels\lib\site-packages\parcels\field.py in from_netcdf(cls, filenames, variable, dimensions, indices, mesh, allow_time_extrapolation, time_periodic, full_load, **kwargs)
    298         else:
    299             time_origin = None
--> 300         assert(np.all((time[1:]-time[:-1]) > 0))
    301 
    302         if time.size == 1 and time[0] is None:

TypeError: '>' not supported between instances of 'datetime.timedelta' and 'int'

**Comment by TKzee2027** [comment]
This is my kernel setup: pset.execute(AdvectionRK4, runtime=timedelta(days=6), dt=timedelta(minutes=5))

**Comment by reint-fischer** [comment]
Hi,

when I run [this example](https://nbviewer.jupyter.org/github/OceanParcels/parcels/blob/master/parcels/examples/parcels_tutorial.ipynb#Reading-in-data-from-arbritrary-NetCDF-files) with your lines, it seems to be working for me:
```
filenames = {'U': "GlobCurrent_example_data/20*.nc",
             'V': "GlobCurrent_example_data/20*.nc"}
variables = {'U': 'eastward_eulerian_current_velocity',
             'V': 'northward_eulerian_current_velocity'}
dimensions = {'lat': 'lat',
              'lon': 'lon'}
timestamps = np.expand_dims(np.arange('2016-07-01T09:00:00', '2016-07-02T17:05:00', dtype='datetime64[5m]'),axis=1)
fieldset = FieldSet.from_netcdf(filenames, variables, dimensions, timestamps=timestamps[:366], allow_time_extrapolation=True)
```
These are the example GlobCurrent data from the `parcels_examples`. Does this code work for you?

Unfortunately, I cannot access your datalink, but I was wondering if you need the timestamps in the first place. Do your data have no time dimension? If you have time in your dimensions in the current version of parcels, parcels disregards the timestamps.

If my lines of code do not work, could you tell me which version of parcels you have installed?

**Comment by TKzee2027** [comment]
Hi

I am using parcels v1.0.1.

I have a time dimension in the data .... this is an example of the data i
am using 20170228000000-GLOBCURRENT-L4-CURgeo_0m-ALT_OI_NRT-v03.0-fv01.0.nc

I have allocated sharing rights to all the email addresses.

Thank you
Tshikana

**Comment by reint-fischer** [comment]
Hi Tshikana,

Can you then run the simulation without specifying the timestamps? They should not be necessary.

Also, if you could update to a newer version of parcels, this should work and it would be easier to comment on errors.

good luck!

**Comment by TKzee2027** [comment]
Thank you,

I will update the parcels right away.

Thank you once again.

**Comment by TKzee2027** [comment]
Thank you, the code ran after updating parcels to v2.2.0, however, when
running the kernel  (pset.execute(AdvectionRK4, runtime=timedelta(days=7),
dt=timedelta(minutes=5))) it returns the following error:

AttributeError: 'DeferredArray' object has no attribute 'flags'


Thanks

Tshikana

**Comment by reint-fischer** [comment]
HI Tshikana,

good to hear that your initial problem was resolved.

Without the full error message it is difficult to see the problem, could you share those?

Reint

**Comment by TKzee2027** [comment]
Hi Reint. I am sorry about this back and forth, and thank you for helping me.

I have closed the script and after running it returns a different error message - here are the data variables from one of the globcurrent file - 
variables.keys()
 dict_keys(['time', 'lat', 'lon', 'eastward_geostrophic_current_velocity', 'eastward_geostrophic_current_velocity_error', 'northward_geostrophic_current_velocity', 'northward_geostrophic_current_velocity_error'])**


KeyError                                  Traceback (most recent call last)
~\Anaconda3\envs\py3_parcels\lib\site-packages\xarray\core\dataset.py in _construct_dataarray(self, name)
    895         try:
--> 896             variable = self._variables[name]
    897         except KeyError:

KeyError: 'eastward_geotrophic_current_velocity'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-29-e1e9eab5659e> in <module>()
----> 1 pset.execute(AdvectionRK4, runtime=timedelta(days=7), dt=timedelta(minutes=5))

~\Anaconda3\envs\py3_parcels\lib\site-packages\parcels\particleset.py in execute(self, pyfunc, endtime, runtime, dt, moviedt, recovery, output_file, movie_background_field, verbose_progress)
    399         next_output = time + outputdt if dt > 0 else time - outputdt
    400         next_movie = time + moviedt if dt > 0 else time - moviedt
--> 401         next_input = self.fieldset.computeTimeChunk(time, np.sign(dt))
    402 
    403         tol = 1e-12

~\Anaconda3\envs\py3_parcels\lib\site-packages\parcels\fieldset.py in computeTimeChunk(self, time, dt)
    760                 f.loaded_time_indices = range(3)
    761                 for tind in f.loaded_time_indices:
--> 762                     f.computeTimeChunk(data, tind)
    763                 f.data = f.reshape(data)
    764             elif g.update_status == 'updated':

~\Anaconda3\envs\py3_parcels\lib\site-packages\parcels\field.py in computeTimeChunk(self, data, tindex)
    973             if self.netcdf_engine != 'xarray':
    974                 filebuffer.name = filebuffer.parse_name(self.filebuffername)
--> 975             if len(filebuffer.data.shape) == 2:
    976                 data[tindex, 0, :, :] = filebuffer.data
    977             elif len(filebuffer.data.shape) == 3:

~\Anaconda3\envs\py3_parcels\lib\site-packages\parcels\field.py in data(self)
   1484             data = self.dataset
   1485         else:
-> 1486             data = self.dataset[self.name]
   1487         ti = range(data.shape[0]) if self.ti is None else self.ti
   1488         if len(data.shape) == 2:

~\Anaconda3\envs\py3_parcels\lib\site-packages\xarray\core\dataset.py in __getitem__(self, key)
    968 
    969         if hashable(key):
--> 970             return self._construct_dataarray(key)
    971         else:
    972             return self._copy_listed(np.asarray(key))

~\Anaconda3\envs\py3_parcels\lib\site-packages\xarray\core\dataset.py in _construct_dataarray(self, name)
    897         except KeyError:
    898             _, name, variable = _get_virtual_variable(
--> 899                 self._variables, name, self._level_coords, self.dims)
    900 
    901         coords = OrderedDict()

~\Anaconda3\envs\py3_parcels\lib\site-packages\xarray\core\dataset.py in _get_virtual_variable(variables, key, level_vars, dim_sizes)
     72         ref_var = dim_var.to_index_variable().get_level_variable(ref_name)
     73     else:
---> 74         ref_var = variables[ref_name]
     75 
     76     if var_name is None:

KeyError: 'eastward_geotrophic_current_velocity'

**Comment by TKzee2027** [comment]
There was an error in one of the files - This is solved now. Thank you so much, Reint
