### ISSUE TITLE
Tutorial plotting does not work on macOS from v2.1.5

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/parcels#799]
As reported by @climatedynamics_twitter on [gitter](https://gitter.im/OceanPARCELS/parcels_installation),  the Parcels jupyter tutorial does not show plots on macOS, with an error `Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.` This bug was introduced in v2.1.5, through commit https://github.com/OceanParcels/parcels/pull/787/commits/262681bcd8a7feb7bbc167fa52e25fb37b240675.

While the solution that @climatedynamics_twitter proposed, to `import tkinter` works for some cells, I then get a `AttributeError: 'GeoAxesSubplot' object has no attribute '_hold'` in Cell 23. This needs to be fixed
