### ISSUE TITLE
Exception with version 2.1.4 in Python 3.8

### ISSUE THREAD

**Issue by albertotb** [OceanParcels/parcels#752]
If I create an environment with Python 3.8

     conda create -n py38_parcels -c conda-forge python>=3.8 parcels jupyter cartopy ffmpeg

activate it

    conda activate py38_parcels

and run the examples

    python example_peninsula.py --fieldset 100 100

I get the following error

```
INFO: Generating FieldSet output with basename: peninsula
WARNING: Particle initialisation from field can be very slow as it is computed in scipy mode.
Peninsula: Advecting 20 particles for 1 day, 0:00:00
Traceback (most recent call last):
  File "example_peninsula.py", line 206, in <module>
    peninsula_example(fieldset, outfile, args.particles, mode=args.mode,
  File "example_peninsula.py", line 118, in peninsula_example
    pset.execute(k_adv + k_p, runtime=time, dt=dt, output_file=out)
  File "/home/atorres/miniconda3/envs/py38_parcels/lib/python3.8/site-packages/parcels/kernel.py", line 387, in __add__
    return self.merge(kernel)
  File "/home/atorres/miniconda3/envs/py38_parcels/lib/python3.8/site-packages/parcels/kernel.py", line 379, in merge
    return Kernel(self.fieldset, self.ptype, pyfunc=None,
  File "/home/atorres/miniconda3/envs/py38_parcels/lib/python3.8/site-packages/parcels/kernel.py", line 117, in __init__
    exec(compile(py_mod, "<ast>", "exec"), user_ctx)
TypeError: required field "type_ignores" missing from Module
Exception ignored in: <function ParticleFile.__del__ at 0x7fb778d9c940>
Traceback (most recent call last):
  File "/home/atorres/miniconda3/envs/py38_parcels/lib/python3.8/site-packages/parcels/particlefile.py", line 195, in __del__
    self.close()
  File "/home/atorres/miniconda3/envs/py38_parcels/lib/python3.8/site-packages/parcels/particlefile.py", line 200, in close
    self.export()
  File "/home/atorres/miniconda3/envs/py38_parcels/lib/python3.8/site-packages/parcels/particlefile.py", line 350, in export
    raise RuntimeError("No npy files found in %s" % self.tempwritedir_base)
RuntimeError: No npy files found in out-EMKLQHPA
Exception ignored in: <function Pool.__del__ at 0x7fb781ec7040>
Traceback (most recent call last):
  File "/home/atorres/miniconda3/envs/py38_parcels/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
  File "/home/atorres/miniconda3/envs/py38_parcels/lib/python3.8/multiprocessing/queues.py", line 362, in put
AttributeError: 'NoneType' object has no attribute 'dumps'
```

This works fine in an environment with Python 3.6. 

If it helps, in different code that used to work I get this exception in Python 3.8 , which I assume it is related. It seems there is a weird error with JIT compiling the kernel, like it could not handle the docstring (it is the kernel from the documentation [here](http://oceanparcels.org/gh-pages/html/_modules/parcels/kernels/advection.html))

```
Traceback (most recent call last):
  File "/home/atorres/miniconda3/envs/satlink-data-service/lib/python3.8/site-packages/parcels/compiler.py", line 55, in compile
    subprocess.check_call(cc, stdout=logfile, stderr=logfile)
  File "/home/atorres/miniconda3/envs/satlink-data-service/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gcc', '-Wall', '-fPIC', '-I/home/atorres/miniconda3/envs/satlink-data-service/lib/python3.8/site-packages/parcels/include', '-g', '-O3', '-m64', '-o', '/tmp/parcels-1028/5ddba0258552df9520c6e8039e993e1c_0.so', '/tmp/parcels-1028/5ddba0258552df9520c6e8039e993e1c_0.c', '-shared', '-m64']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/atorres/miniconda3/envs/satlink-data-service/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/atorres/miniconda3/envs/satlink-data-service/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/atorres/miniconda3/envs/satlink-data-service/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/atorres/satlink-data-service/nucleus/views.py", line 49, in simulate_view
    ret = simulate(*args, **kwargs)
  File "/home/atorres/satlink-data-service/nucleus/simulate.py", line 189, in simulate
    pset.execute(#pset.Kernel(StochasticAdvectionRK4),
  File "/home/atorres/miniconda3/envs/satlink-data-service/lib/python3.8/site-packages/parcels/particleset.py", line 382, in execute
    self.kernel.compile(compiler=GNUCompiler(cppargs=cppargs))
  File "/home/atorres/miniconda3/envs/satlink-data-service/lib/python3.8/site-packages/parcels/kernel.py", line 211, in compile
    compiler.compile(self.src_file, self.lib_file, self.log_file)
  File "/home/atorres/miniconda3/envs/satlink-data-service/lib/python3.8/site-packages/parcels/compiler.py", line 68, in compile
    raise RuntimeError(err)
RuntimeError: Error during compilation:
Compilation command: gcc -Wall -fPIC -I/home/atorres/miniconda3/envs/satlink-data-service/lib/python3.8/site-packages/parcels/include -g -O3 -m64 -o /tmp/parcels-1028/5ddba0258552df9520c6e8039e993e1c_0.so /tmp/parcels-1028/5ddba0258552df9520c6e8039e993e1c_0.c -shared -m64
Source file: /tmp/parcels-1028/5ddba0258552df9520c6e8039e993e1c_0.c
Log file: /tmp/parcels-1028/5ddba0258552df9520c6e8039e993e1c_0.log

Log output: In file included from /tmp/parcels-1028/5ddba0258552df9520c6e8039e993e1c_0.c:1:0:
/home/atorres/miniconda3/envs/satlink-data-service/lib/python3.8/site-packages/parcels/include/parcels.h: In function ‘spatial_interpolation_UVW_c_grid’:
/home/atorres/miniconda3/envs/satlink-data-service/lib/python3.8/site-packages/parcels/include/parcels.h:598:34: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
     float (*zvals)[ydim][xdim] = (float (*)[zdim][ydim][xdim]) grid->depth;
                                  ^
/tmp/parcels-1028/5ddba0258552df9520c6e8039e993e1c_0.c: In function ‘AdvectionRK4’:
/tmp/parcels-1028/5ddba0258552df9520c6e8039e993e1c_0.c:53:3: error: unknown type name ‘Advection’
   Advection of particles using fourth-order Runge-Kutta integration.
   ^
/tmp/parcels-1028/5ddba0258552df9520c6e8039e993e1c_0.c:53:16: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘particles’
   Advection of particles using fourth-order Runge-Kutta integration.
                ^
/tmp/parcels-1028/5ddba0258552df9520c6e8039e993e1c_0.c: In function ‘particle_loop’:
/tmp/parcels-1028/5ddba0258552df9520c6e8039e993e1c_0.c:128:15: warning: suggest parentheses around comparison in operand of ‘&’ [-Wparentheses]
       if (res == SUCCESS & __pdt_prekernels != particles[p].dt)
               ^
```

**Comment by erikvansebille** [comment]
Thanks for reporting this, @albertotb. I've opened a PR at #753 which addresses the ast Issue that you report. However, at least two other errors pop up after that one, so more work needs to be done before Parcels works with python3.8

Can you not keep working with python3.6 for now? Or could you help us find solutions to these outstanding points in #753?

**Comment by albertotb** [comment]
Thanks for the quick reply. Yes, I just downgraded to Python 3.6. I'll take a look at the PR in case there is anything I can do to help, although I'm not a JIT expert.

**Comment by erikvansebille** [comment]
Fixed in #753
